### ISSUE TITLE
Please make a new tag

### ISSUE THREAD

**Issue by linzening** [tecnickcom/TCPDF#324] opened 2021-02-07 07:43 UTC
Please make a new tag,for php8.0,thanks.

**Comment by jansor** [comment] 2021-02-16 08:51
@nicolaasuni Any idea when we can expect a new release for PHP8.0

**Comment by mstyles** [comment] 2021-02-16 17:48
this is a duplicate of https://github.com/tecnickcom/TCPDF/issues/318

**Comment by nicolaasuni** [comment] 2021-03-27 09:25
I have merged today all pending PRs.
Please consider contributing to https://github.com/tecnickcom/tc-lib-pdf

**Closed by nicolaasuni** 2021-03-27 09:25 UTC
